title: "willclark.tech"
tagline: "return ai || security || privacy || tech tips"
description: "return ai || security || privacy || tech tips"
production_url: "https://blog.willclark.tech"
author:
  name: "Will Clark"
  website: "willclark.tech"
  email: "will@willclark.tech"
  github: "willclarktech"
  twitter: "willclarktech"

theme: "jekyll-theme-cayman"
paginate: 10

disqus_short_name: "willclarktech"

twitter:
  username: "willclarktech"

social:
  name: "willclarktech"
  links:
    - "https://twitter.com/willclarktech"
    - "https://github.com/willclarktech"

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "CNAME"
  - "README.md"
  - "scripts/"
